"""
Phonon Calculation Example using AtomChain

This example demonstrates the new phonon workflow:
1. Calculate phonon properties using frozen phonon method
2. All phonon files are saved to phonon_save/ subdirectory
3. Plot phonon band structure using ASE k-path generation

Requirements:
- Pre-trained ML potential (e.g., mace_mp model)
- Structure file (VASP format)

Usage:
    python phonon_example.py

Expected behavior:
- Creates phonon_save/ directory with all phonon calculation files
- Generates phonon band structure plot (phonon_bands.png)
- Output files: disp.yaml, FORCE_CONSTANTS, phonon.pickle, etc.
"""

from ase.io import read

# Note: Import paths changed in refactor - phonon modules moved to phonon/ subdirectory
from atomchain.phonon.frozenphonon import calculate_phonon
from atomchain.phonon.plotphonopy import plot_phonon

try:
    from mace.calculators import mace_mp
except ImportError:
    print("MACE not installed. Install with: pip install mace-torch")
    exit(1)


def main():
    """Run phonon calculation example."""

    # Step 1: Load structure
    print("Loading Al FCC structure...")
    atoms = read("Al_fcc.vasp")

    # Step 2: Initialize ML calculator
    print("Initializing MACE-MP calculator...")
    calc = mace_mp(
        model="medium", dispersion=False, default_dtype="float64", device="cpu"
    )
    atoms.calc = calc

    # Step 3: Calculate phonons
    # All files will be saved to phonon_save/ subdirectory
    print("\nCalculating phonons using frozen phonon method...")
    print("This will create phonon_save/ directory with all output files")

    calculate_phonon(
        atoms,
        calc=calc,
        supercell_matrix=[[2, 0, 0], [0, 2, 0], [0, 0, 2]],  # 2x2x2 supercell
        displacement=0.01,  # Displacement in Angstrom
        phonon_save_dir="phonon_save",  # Output directory (default)
    )

    print("✓ Phonon calculation complete!")
    print("  Files saved to: phonon_save/")

    # Step 4: Plot band structure
    print("\nPlotting phonon band structure...")
    print("Using ASE automatic k-path generation for FCC structure")

    plot_phonon(
        path="phonon_save",  # Read from phonon_save/ directory
        kpath="GXWKGLUWLK",  # Standard FCC k-path (will be generated by ASE)
        figname="phonon_bands.png",
        show=False,  # Don't show interactively, just save
        units="cm-1",  # Use cm^-1 units (default)
    )

    print("✓ Band structure plot saved to: phonon_bands.png")

    # Summary
    print("\n" + "=" * 60)
    print("PHONON CALCULATION SUMMARY")
    print("=" * 60)
    print("Structure: Al FCC (1 atom)")
    print("Supercell: 2x2x2")
    print("Output directory: phonon_save/")
    print("\nKey files:")
    print("  - phonon_save/disp.yaml           : Displacement info")
    print("  - phonon_save/FORCE_CONSTANTS     : Force constants")
    print("  - phonon_save/phonon.pickle       : Phonopy object")
    print("  - phonon_save/phonopy_params.yaml : Phonopy parameters")
    print("  - phonon_bands.png                : Band structure plot")
    print("=" * 60)


if __name__ == "__main__":
    main()
